### PR TITLE
Use `TaskCollection.named` overload taking `Spec`

### PR DESCRIPTION
**Pull request by lukellmann**
Use the new `TaskCollection.named` method taking a `Spec` for depending on tasks that might not exist.

See https://docs.gradle.org/8.6/release-notes.html#lazy-name-based-filtering-of-tasks

### CODE REVIEW

**Comment by lukellmann** [comment]
btw, what the reason for [this commit](https://github.com/kordlib/gradle-tools/commit/b11bab85077ebcec358a899a0dee1050e76ad299)? asking to make sure this won't conflict with that change.

**Comment by DRSchlaubi** [comment]
For some reason named thrw an exception when the task doesn't exist. Did you test this on kord

**Comment by lukellmann** [comment]
> Did you test this on kord

not yet, how would i best do this?

**Comment by DRSchlaubi** [comment]
Push to Maven local

**Comment by lukellmann** [comment]
> For some reason named thrw an exception when the task doesn't exist.

makes sense, it's documented to do so: https://docs.gradle.org/current/javadoc/org/gradle/api/NamedDomainObjectCollection.html#named-java.lang.String-

**Comment by DRSchlaubi** [comment]
ig this doesn't matter when using the predicate

**Comment by lukellmann** [comment]
yes, it's just gonna be an empty collection and `dependsOn` seems to just accept that

**Comment by lukellmann** [comment]
> Did you test this on kord

i did, it works after fixing [this npe](https://github.com/kordlib/gradle-tools/pull/1/commits/cef73c7502c8d976f834251c80a4118cab6e10a6) and running kord's build with gradle 8.6

**Comment by lukellmann** [comment]
with https://github.com/kordlib/kord/pull/920 kord will use gradle 8.6

**Pull request merged**
